---
version: "3.8"

volumes:
  goth-redis:
  goth-postgres:

networks:
  goth:
  proxy:
    external: true

services:
  goth-redis:
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    container_name: goth-redis
    image: redis:alpine
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - goth-redis:/data
    networks: [goth]
    ports: [6379:6379]   # Disable ports in production

  goth-postgres:
    security_opt: [no-new-privileges:true]
    restart: unless-stopped
    container_name: goth-postgres
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - goth-postgres:/var/lib/postgresql/data
    networks: [goth]
    ports: [5432:5432]   # Disable ports in production

