// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	UserCreate(ctx context.Context, arg UserCreateParams) (User, error)
	UserDelete(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	UserRead(ctx context.Context, id uuid.UUID) (User, error)
	UserReadByEmail(ctx context.Context, email string) (User, error)
}

var _ Querier = (*Queries)(nil)
