// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	UserCreate(ctx context.Context, arg UserCreateParams) (User, error)
	UserDelete(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	UserRead(ctx context.Context, id uuid.UUID) (User, error)
	UserReadByEmail(ctx context.Context, email string) (User, error)
	UserReadByUsername(ctx context.Context, username string) (User, error)
	UserReadMaster(ctx context.Context) (User, error)
	UserUpdate(ctx context.Context, arg UserUpdateParams) (User, error)
	UserUpdateVerified(ctx context.Context, arg UserUpdateVerifiedParams) (User, error)
	UsersRead(ctx context.Context, arg UsersReadParams) ([]User, error)
}

var _ Querier = (*Queries)(nil)
