package migrations

import (
	"github.com/golang-migrate/migrate/v4"
	_ "github.com/golang-migrate/migrate/v4/database"
	_ "github.com/golang-migrate/migrate/v4/database/postgres"
	_ "github.com/golang-migrate/migrate/v4/source/file"
	bindata "github.com/golang-migrate/migrate/v4/source/go_bindata"
	_ "github.com/lib/pq"
)

// MigrateUsersRepo applies database migrations using the `go-bindata` package as the source driver.
// It creates a migration source using the binary data generated by the `migrations` package, and then
// creates a new migrate instance with the `go-bindata` source driver and the provided database URL. It
// then applies any pending migrations to the database and logs the result.
//
// Usage:
// import "github.com/username/repo/migrations"  // path to generated go-bindata
//
//	if err = database.MigrateUsersRepo(migrations.AssetNames(), migrations.Asset); err != nil {
//		logr.Fatal().Err(err).Msg("failed to migrate database")
//	}
//
// For Reference: https://github.com/sirjager/trueauth/blob/master/main.go
func MigrateUsersRepo(postgresURL string) (err error) {
	// migration binary data
	migrationSource := bindata.Resource(AssetNames(), Asset)
	sourceDriver, err := bindata.WithInstance(migrationSource)
	if err != nil {
		return err
	}

	dbmigrate, err := migrate.NewWithSourceInstance("go-bindata", sourceDriver, postgresURL)
	if err != nil {
		return err
	}
	err = dbmigrate.Up()
	if err != nil {
		// Check if the error is "no change" which indicates that there are no pending migrations.
		// Log an info message in this case.
		if err != migrate.ErrNoChange {
			return err
		}
		// no error is returned if there are no pending migrations
		// so its a success condition
		// log something here
	}
	return nil
}
